#! usr/bin/env php
<?php

namespace Structural\Proxy;

require_once 'vendor/autoload.php';

$proxy = new SubjectProxy();

$proxy->setAssoc('key1', 'value1');
$proxy->setAssoc('key2', 'value2');
$proxy->setAssoc('key3', 'value3');

printf("%s\n", $proxy->getJson());
